package de.joesst.dev.fulfillmenttools.externalactions;

import java.time.Instant;
import java.util.List;
import java.util.Map;

/**
 * Represents an external action returned by the fulfillmenttools API.
 *
 * <p>Maps to the {@code ExternalAction} schema (which composes
 * {@code ExternalActionForReplacement} and {@code VersionedResource}) in the fulfillmenttools
 * OpenAPI spec.
 *
 * <p>Thread-safety: immutable record; safe for concurrent use.
 *
 * @param id              unique identifier generated by the platform (required)
 * @param version         optimistic-locking version counter (required)
 * @param created         timestamp when this entity was created
 * @param lastModified    timestamp when this entity was last modified
 * @param name            non-localized display name (required)
 * @param processRef      ID of the global process this action belongs to (required)
 * @param nameLocalized   localized display names; key is locale (e.g. {@code "en_US"}),
 *                        value is translation (required)
 * @param action          the typed action definition (required)
 * @param groups          user-defined grouping tags (required)
 * @param customAttributes free-form custom attributes; keys and values are arbitrary
 */
public record ExternalAction(
        String id,
        Integer version,
        Instant created,
        Instant lastModified,
        String name,
        String processRef,
        Map<String, String> nameLocalized,
        ExternalActionDefinition action,
        List<String> groups,
        Map<String, Object> customAttributes
) {}
