package de.joesst.dev.fulfillmenttools.externalactions;

import de.joesst.dev.fulfillmenttools.id.ExternalActionId;
import de.joesst.dev.fulfillmenttools.id.ProcessId;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import de.joesst.dev.fulfillmenttools.model.CustomAttributes;

/**
 * Represents an external action returned by the fulfillmenttools API.
 *
 * <p>Maps to the {@code ExternalAction} schema (which composes
 * {@code ExternalActionForReplacement} and {@code VersionedResource}) in the fulfillmenttools
 * OpenAPI spec.
 *
 * <p>Thread-safety: immutable record; safe for concurrent use.
 *
 * @param id              unique identifier generated by the platform (required)
 * @param version         optimistic-locking version counter (required)
 * @param created         timestamp when this entity was created
 * @param lastModified    timestamp when this entity was last modified
 * @param name            non-localized display name (required)
 * @param processRef      ID of the global process this action belongs to (required)
 * @param nameLocalized   localized display names; key is locale (e.g. {@code "en_US"}),
 *                        value is translation (required)
 * @param action          the typed action definition (required)
 * @param groups          user-defined grouping tags (required)
 * @param customAttributes free-form custom attributes; keys and values are arbitrary
 */
public record ExternalAction(
        ExternalActionId id,
        Integer version,
        Instant created,
        Instant lastModified,
        String name,
        ProcessId processRef,
        Map<String, String> nameLocalized,
        ExternalActionDefinition action,
        List<String> groups,
        CustomAttributes customAttributes
) {

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private Builder() {}

        private ExternalActionId id;
        private Integer version;
        private Instant created;
        private Instant lastModified;
        private String name;
        private ProcessId processRef;
        private Map<String, String> nameLocalized;
        private ExternalActionDefinition action;
        private List<String> groups;
        private CustomAttributes customAttributes;

        public Builder id(ExternalActionId id) {
            this.id = id;
            return this;
        }

        public Builder version(Integer version) {
            this.version = version;
            return this;
        }

        public Builder created(Instant created) {
            this.created = created;
            return this;
        }

        public Builder lastModified(Instant lastModified) {
            this.lastModified = lastModified;
            return this;
        }

        public Builder name(String name) {
            this.name = name;
            return this;
        }

        public Builder processRef(ProcessId processRef) {
            this.processRef = processRef;
            return this;
        }

        public Builder nameLocalized(Map<String, String> nameLocalized) {
            this.nameLocalized = nameLocalized;
            return this;
        }

        public Builder action(ExternalActionDefinition action) {
            this.action = action;
            return this;
        }

        public Builder groups(List<String> groups) {
            this.groups = groups;
            return this;
        }

        public Builder customAttributes(CustomAttributes customAttributes) {
            this.customAttributes = customAttributes;
            return this;
        }

        public ExternalAction build() {
            return new ExternalAction(id, version, created, lastModified, name, processRef,
                    nameLocalized, action, groups, customAttributes);
        }
    }
}
